- api/controllers/AuthController.js
- api/controllers/UserController.js
- config/express.js
- config/routes.js
...wheee. More tested than last time.
> Fixed mod permissions

- api/controllers/UserController.js
- assets/js/banCtrl.js
- views/privacyPolicy.ejs
1. Removed the lines in the Privacy Policy explaining why we need permission to access the user's flairs (since we don't need that anymore)
2. Improved the server-side checks for the ban function to make sure the received input is valid. (Never trust the client, etc.) Also added a few clientside checks to make sure the username and duration are valid.
> A few non-essential improvements

- api/controllers/FlairController.js
- api/controllers/UserController.js
- api/services/Flairs.js
- api/services/Reddit.js
- assets/js/adminCtrl.js
- assets/js/banCtrl.js
- assets/js/refCtrl.js
- node_modules/node-sha1/.npmignore
- node_modules/node-sha1/.travis.yml
- node_modules/node-sha1/README.md
- node_modules/node-sha1/lib/sha1.js
- node_modules/node-sha1/package.json
- node_modules/node-sha1/spec/sha1-spec.js
- node_modules/node-sha1/spec/support/jasmine.json
- package.json
- views/home/banlist.ejs
- views/home/modEdit.ejs
Changelog:
1. /u/FlairHQ now sends an automatic approval message when a flair application is approved.
2. The client-side local ban/unban buttons are back, due to popular demand.
3. /u/FlairHQ sends a modmail if someone sets a flair with invalid friend codes.
There are a few preparations required for this to work properly:
1. node-sha1 needs to be installed, if it's not already. `npm install node-sha1 --save`
2. /u/FlairHQ should be reauthenticated with the `privatemessages` scope added on, and `sails.config.reddit.adminRefreshToken` should be updated with the new token. Make sure /u/FlairHQ still has at least `modflair` scope as well, otherwise flairs won't appear on the index page.
> Private messages

- assets/js/userCtrl.js
TIL that egg giveaways count towards ribbon flair on SVeX.
> Woohoo another pull request

- assets/js/indexCtrl.js
- assets/js/refCtrl.js
> Fix bug which prevented tradebacks from being edited

- assets/js/userCtrl.js
> Prevent users from applying for lower flairs than they already have

- assets/js/userCtrl.js
> Fixed an issue which was causing a client error

- api/controllers/UserController.js
- api/services/Ban.js
- api/services/Reddit.js
Also, TSV threads will now get marked as 'not spam' instead of 'spam' when they're removed.
> Fixed serverside check which was preventing permabans

- api/controllers/FlairController.js
If user didn't already have flair set ever, it would crash here.
> Fix small error

- api/controllers/ReferenceController.js
- api/controllers/UserController.js
- config/routes.js
- views/home/viewreference.ejs
> Fixed a few security issues

- api/controllers/ReferenceController.js
- api/services/Ban.js
- api/services/Reddit.js
- config/debug_vars.js
> A few small fixes

- api/controllers/ReferenceController.js
> Fixed error message

- assets/js/adminCtrl.js
- assets/js/userCtrl.js
- views/home/applist.ejs
- views/home/flairApply.ejs
[Example image](https://i.gyazo.com/e83f784defc0116b37c619ac116794a7.png)
This will probably conflict with your babeljs PR, do with it as you will.
> Flair app list now displays flair requirements on mouseover

- api/controllers/FlairController.js
- api/controllers/HomeController.js
- api/controllers/UserController.js
- api/services/Reddit.js
- config/debug_vars.js
- config/express.js
Got rid of a lot of redundant code.
> Reddit.js cleanup

- api/services/Reddit.js
- assets/js/userCtrl.js
Resolves #351
edit: Also resolves #353, an unrelated issue which I didn't feel like making a separate pull request for.
> Fixed flair-getting issue

- api/controllers/FlairController.js
- api/controllers/UserController.js
- api/services/Ban.js
- api/services/Reddit.js
- config/express.js
Now Reddit.js correctly identifies an error if Reddit returns something other than a 200 response.
> Fixed error handling

- config/policies.js
Oops. I should have known I'd make a typo somewhere.
> Fixed policy error

- api/controllers/FlairController.js
- assets/js/userCtrl.js
- views/home/flairApply.ejs
Resolves #361
Update: Also fixes a console-message issue caused by duplicate variables, and a minor string typo.
Update2: The user's cached flair now updates when their flair application is approved. This resolves #241. (See my comment on that issue for more details).
> Titletext now appears on entire button in the 'Apply for flair' menu

- api/controllers/AuthController.js
- api/policies/sessionAuth.js
- api/services/Flairs.js
- assets/js/refCtrl.js
- assets/js/userCtrl.js
'Eggcup Egg' is now called 'Egg Cup'. Resolves the unrelated issues #367 and #368.
> A few fixes

- api/services/Reddit.js
> Fix Reddit.js error

- config/local.example.js
Hopefully I haven't accidentally leaked any secret info.
> Added local.js example file

- assets/js/userCtrl.js
We really have too many duplicate clientside methods. We should move them to serverside.
> Fix 367 again

- api/services/Reddit.js
Now we won't have massive hexdumps printed to the console when reddit's cdn is down.
> Made console message smaller

- api/controllers/HomeController.js
- api/controllers/SearchController.js
- api/controllers/UserController.js
- api/services/Search.js
- assets/js/app.js
- assets/js/searchCtrl.js
- assets/js/userCtrl.js
- assets/styles/importer.less
- config/policies.js
- config/routes.js
- views/403.ejs
- views/404.ejs
- views/500.ejs
- views/home/header.ejs
- views/search/logs.ejs
- views/search/refs.ejs
> 291 log searches

- api/controllers/AuthController.js
- api/controllers/FlairController.js
- api/controllers/UserController.js
Nothing too exciting, just moved some code around. Also, we now check session states from reddit to fix a (potential) security issue.
> Cleaned up a few things

- api/services/References.js
- assets/js/sharedClientFunctions.js
- views/home/references.ejs
[Example](https://i.gyazo.com/fd59836a29900a9bda8f4fbbc2975aac.png)
> Improve giveaway tally, resolves #191

- views/home/references.ejs
- views/home/viewreference.ejs
[Example image](https://i.gyazo.com/25ff7cfa0a51d0e1cb9d01fd6aca9e5a.png)
> Fix tradeback display, resolves #230

- api/controllers/FlairController.js
- api/controllers/UserController.js
- api/services/Ban.js
We can explain a bit more on IRC if necessary.
> Changed some usernote colors

- api/.eslintrc
- api/controllers/FlairController.js
- api/controllers/UserController.js
- api/services/Ban.js
- api/services/Modmails.js
- api/services/Reddit.js
- config/local.example.js
Now we have a Reddit.js helper function to get entire listings of things, so we don't need to deal with pagination for search, modmails, etc. I also refactored the reddit search function to allow for different types of searches in case we need them in the future.
Also changed the banned TSV thread policy. Currently the banned linkflair has text '[Banned User] Trainer Shiny Value' and CSS class 'banned'.
> Changed banned TSV thread behavior, refactored modmail archiving

- api/controllers/FlairController.js
- api/services/Flairs.js
- assets/userCtrl.js
Fixes a few bugs I found while testing.
> Fix #452 and a few other small issues

- api/controllers/FlairController.js
- api/controllers/ReferenceController.js
- api/controllers/UserController.js
- app.js
- assets/views/home/header.ejs
- config/routes.js
- package.json
> Get rid of modmail download option

- api/controllers/AuthController.js
- api/controllers/HomeController.js
- api/controllers/ReferenceController.js
- api/controllers/UserController.js
- api/services/Ban.js
- api/services/Modmails.js
- api/services/Reddit.js
- api/services/References.js
- config/express.js
- config/schedule.js
> Moved everything to sails logging

- api/responses/notFound.js
- assets/styles/importer.less
- assets/views/home/row.ejs
- assets/views/home/viewreference.ejs
- package.json
Fixes #480, fixes #482, fixes #484, fixes #487
> Fix some rendering issues

- assets/sharedClientFunctions.js
- package.json
It doesn't display on a user's profile page at the moment.
> Fix SVeX flair css class issue

- api/services/Modmails.js
It hadn't been working for the past few days.
> Fixed modmail archiving

- assets/userCtrl.js
- assets/views/home/index.ejs
- assets/views/home/references.ejs
Let's merge this before the stuff gets deployed, but probably don't merge it yet, in case we find more things to fix before then.
> Fix some small things

- api/controllers/FlairController.js
A few people suggested this, because sometimes we only see the top of the report and assume it's one of the less important ones.
> Use bold text for important reports

- api/controllers/AuthController.js
- api/controllers/HomeController.js
- api/controllers/ReferenceController.js
- api/controllers/UserController.js
- api/services/Ban.js
- api/services/Modmails.js
- api/services/Reddit.js
- api/services/References.js
- assets/refCtrl.js
- assets/views/home/modEdit.ejs
- assets/views/home/reference.ejs
- config/env/production.js
- config/express.js
- config/schedule.js
- package.json
Development branch for FlairHQ 2.4
Changelog so far:
> Version 2.4

- assets/views/layout.ejs
¯\\\_(ツ)_/¯
Feel free to merge this if you want. Or not. I think it makes the page mildly funnier, anyway. There are no functional changes.
> Make google analytics more fun

- api/controllers/ReferenceController.js
> Include the public notes when adding a reference

- assets/styles/importer.less
The red link colors keep confusing people into thinking something is wrong with their links, and we don't really have a good reason for them to be red, so let's fix it :p
> Change visited link color from red to purple

- assets/styles/importer.less
- assets/views/home/flairText.ejs
To make it more clear what's required and what's not, and also to specify that the starter selection is for /r/pokemontrades.
Preview:
> Edit flair text form labels

- assets/userCtrl.js
- assets/views/home/editreference.ejs
- assets/views/home/index.ejs
- assets/views/home/references.ejs
> Change all frontend copies of "Gen 6 Event" to "Event"

- assets/views/privacyPolicy.ejs
It was recently reported that FlairHQ's privacy policy is a bit out of date. Update the privacy policy to reflect some recent changes.
> Update privacy policy

- api/controllers/FlairController.js
Should prevent the "/u/ is banned" notification when the user is an alt, but not banned.
> Fixes false alarm ban

- assets/tools/tools.ejs
> Changed Greasemonkey for Safari to Tampermonkey

- README.md
Basic steps with some images + a little bit of troubleshooting. Fixes #596.
> Setup instruction for dev environment

- assets/views/home/applist.ejs
Placed date to the right of the username on flair apps so we can see how long they've been up for
Preview of date placement: https://usercontent.irccloud-cdn.com/file/g7cZ39ff/image.png
> Add date to flair app list

- api/controllers/ReferenceController.js
- api/models/Reference.js
- assets/views/home/editreference.ejs
- assets/views/home/index.ejs
> Don't allow negative pokemon/eggs given away

- assets/views/home/references.ejs
Tallies up all the approved trades within the different categories to help a bit with flair apps. 
Preview of approved trades counter: https://usercontent.irccloud-cdn.com/file/r0CDoyma/image.png
> Add approved trades counter

- assets/views/home/applist.ejs
> Improve team morale

- api/controllers/UserController.js
- api/models/User.js
- api/services/Users.js
- assets/views/home/editProfile.ejs
- assets/views/home/modEdit.ejs
- assets/views/home/profileInfo.ejs
From what I tested: if someone edit HTML and try to send it, it won't send "intro" param with the request which is good enough I think.
Again, error in controller is a bit redundant as I was never able to get it (I assume it might be useful if someone tries to hack the app and send request by himself but I wasn't testing it).
Resolves #50 
Edit: I wasn't adding wrap for non-space-extremely-long-words but if we really want it I can look at this.
> Limit size of user introduction to 10 000 chars

- api/services/Reddit.js
Checked with testuser. No error appeared, user has been added successfully to banlist on both of my subs
> Fixed ban length format

- api/services/Ban.js
Fixes #589 by replacing `\_` with `_` and then reverting. The actual issue is that while doing `split(/\s*\|\s*/)` backslash in username causes splitting.
Kind of workaround here but I haven't found any better solution.
> Fix banlist bug

- api/controllers/FlairController.js
Not actually tested, written in about 5 minutes. Good luck.
> Filter out common incorrect fcs from alt check

- api/policies/isPostMod.js
- api/services/Users.js
- assets/views/home/modEdit.ejs
- assets/views/home/reference.ejs
- config/policies.js
Added PostMod functionality. This includes visibility (read only) of usernotes. Edit form is removed unless you have 'all' permission.
PostMod is mod who has both 'wiki' and 'posts' rights over the subreddit.
> Add PostMod functionality

- api/.eslintrc
- api/controllers/AuthController.js
- api/controllers/HomeController.js
- api/models/Event.js
- api/services/Discord.js
- assets/views/home/addDiscord.ejs
- assets/views/home/index.ejs
- config/local.example.js
- config/policies.js
- config/routes.js
- package-lock.json
Todo list:
Must have:
Good to have:
To test: add the Discord bot data and go to http://localhost:1337/discord. It'll return your account info to your browser.
> Authenticating via Discord

- assets/refCtrl.js
- assets/views/home/modEdit.ejs
The API call was already in place, so I added a button in the mod section of a user's profile (#655). This clears the user's sessions, or shows an error message if it failed.
> Add mod button to clear user sessions

- assets/styles/importer.less
Fix the checkbox in Firefox...
#618
> Fix Checkbox in Firefox

- api/controllers/FlairController.js
This fixes a bug which results in incorrect alt account notifications.
> Fix alt check

- assets/views/home/flairApply.ejs
- assets/views/home/flairText.ejs
* Adds message on flair application page about Pokeball flair being prioritized due to high volume
* Changes "Giveaway-er" header text under SVExchange to "Helper"
* Adds message on flair setting page about reddit accounts needing to be 15 days old to post
> Update flair application / flair setting pages
