api/controllers/ReferenceController.js
api/models/Reference.js
api/services/References.js
assets/styles/importer.less
views/home/references.ejs

Resolves #4
When a mod approves a User A's trade with User B, the server checks if User B also logged that url in a trade with User A. If they did, user B's version of the trade is also marked as approved. Both versions are also marked as 'verified'. Verified trades display a [green checkmark](https://i.gyazo.com/62cb32c7ad9458b1ce4e4a60036e209b.png) next to the approval box, only visible to mods.
If either user edits their version of the trade, that version of the trade will be un-approved as normal, but the other user's version will remain approved. Both trades will remain verified.
If a mod un-approves either version of the trade, both versions become non-approved and non-verified.
If a version of the trade gets deleted (either by its owner or a mod), the other version will become …

Implemented trade verification

---

api/controllers/FlairController.js
api/controllers/HomeController.js
api/controllers/UserController.js
api/models/Event.js
config/debug_vars.js
config/routes.js

* The user who approves a flair app or bans someone is now logged on the console.
* The automated approval PM now tells the user the subreddit that their flair was approved on, in case they forgot or something.
* Approval PMs are no longer logged on the console (they're redundant since "Changed flair" events are logged)
* The current version of FlairHQ can be accessed at /version, only accessible to mods.
* A new Event is created when a user is banned.

Improved a few things

---

api/controllers/FlairController.js
config/express.js

Now flair gets set correctly when users log in. (It generally doesn't matter since the flairs get set again when the user loads the index page, but we still shouldn't have buggy code here.) The function was being called with the two flairs in the second and third parameters, but it was checking for the flairs in the first and second parameters.
Also, I fixed something so that modmail spam will be reduced. It will no longer send a modmail if the friendcode matches their most-recently-logged one (i.e. if a modmail was just sent with that friendcode). However, it will send a modmail if the user's FC changes from valid to invalid, or invalid to some-other-invalid.

Fixed small thing with login

---

assets/js/indexCtrl.js
assets/js/sharedClientFunctions.js

It's not extremely clear from the diff, but now the `addReference()` and `editRef()` functions both call a new method `validateRef()` to check validity, rather than having duplicate checks in both functions.

Combined clientside trade validity check for adding and editing

---

api/services/Search.js
assets/search/header.ejs
assets/search/main.ejs
assets/search/modmail/controller.js
assets/search/modmail/form.ejs
assets/search/modmail/result.ejs
assets/search/search.controller.js
assets/search/types.js
assets/userCtrl.js
config/policies.js
config/routes.js

Adds modmail search, refactors a few small things, fixes some bugs.
Is there a reason why we have three separate strings (`long`, `short`, and `name`) to describe each search type? It seems like we could simplify things by just using `name` for everything (including the routes and the serverside stuff).

Added modmail search, refactored things

---

api/controllers/FlairController.js
assets/js/userCtrl.js

* #418: People with default flair on svex can't set their flair text
* #420: No one can apply for flair
___
* Cause of 418: lodash.get uses the default case when the path is `undefined`, but we want the default case to get used whenever the path is falsey. It's running into trouble when the flair css class is `null`.
* Cause of 420: Messed-up function call from clientside refactor

Fix #418 and #420

---

assets/views/home/header.ejs
config/views.js
package.json
tasks/config/browserify.js
tasks/config/watch.js
tasks/register/default.js

Finish off removing user-specific stuff in the header for angular. That's one step closer to javascript-less working. 
Also, made the watch much quicker, multiple ways. 
Fixes #427 
Also fixes #426

Watch and header

---

api/policies/sessionAuth.js
assets/views/home/banlist.ejs
assets/views/home/editreference.ejs
assets/views/home/index.ejs
package.json

Wow, this was a great bug.
We were rendering banned users in a somewhat inefficient way; we used a combination of angular and EJS. We got the array of banned users like this:
```html
<li ng-repeat="user in <%= JSON.stringify(bannedUsers) %>" class="list-group-item row">
```
The `bannedUsers` local was actually the entire user object rather than just the username, so after EJS compiled it, it looked like this:
```html
<li ng-repeat="user in {&quot;name&quot; : &quot;naa&quot; , &quot;intro&quot; : &quot;blah&quot; , ...}" class="list-group-item row">
```
This all worked fine, until there was a user that had the string " as " in their intro. Then the line got compiled to:
```html
<li ng-repeat="user in {&quot;name&quot; : &quot;naa&quot; , &quot;intro&quot; : &quot;blah as blah&quot; , …
```

Fix #495, fix #498, fix #500

---

package.json

Personally I find this hilarious.
Anyway, as a result of this, modmails haven't been archived since January 31st. I just updated the dependency on the server (by running npm upgrade), but we should still probably update the repo as well.
Update: I also fixed the sails-hook-babel issue, so now the app should build properly again.

Fixed sails-hook-schedule, which broke since this is a leap month

---

api/services/Flairs.js
assets/userCtrl.js
package.json
test/unit/data/flairTexts.json
test/unit/services/Flairs.test.js

We weren't validating TSVs in SVeX flairs, so it was possible for people to put anything they wanted at the end of their SVeX flair.

Fix a slight security issue

---

assets/sharedClientFunctions.js
assets/views/home/row.ejs
package.json

It's been two months, so most people probably aren't using it anymore, and it was added as a temporary feature anyway.

Get rid of the 'move to shiny section' button

---

api/controllers/UserController.js
config/routes.js

Using a GET request creates a small security issue since it can be linked and activated from other places. It doesn't allow people to do anything other than be annoying on a small scale, but it's still a good idea to get rid of.
There's still no frontend for this, but it's done rarely enough that we can just construct the request from the dev console whenever we need to actually use it.

Explicitly specify POST/GET requests in config/routes.js

---

.travis.yml

It seems travis uses the bundled version of npm with node, so let's install the newest version, because it looks like we are having some semver bugs with the greenkeeper PR.

Update npm version on travis

---

api/services/Flairs.js
package.json

Added another condition to the flair suffixes so that the new flair will be displayed as "Gen II Egg" rather than "Gen2 Egg" and bumped the version to 2.5.1.

Fixed display of Gen II Ball's name and bumped version number

---

assets/search/search.controller.js
package.json

This makes it so that trade search results link to the trade in question, rather than the user profile of whoever logged the trade.

Link to the trade instead of the user's reference page on search

---

api/services/Flairs.js

This would occur if a user was banned and they had never set a flair on either sub. The issue was that `Flairs.parseGames` would parse an empty-string flair text as `[{ign: undefined, game: ''}]` instead of realizing that the flair text contained no games.

Fix an issue where `undefined` could appear on the banlist

---

api/.eslintrc
api/controllers/ReferenceController.js
api/services/References.js

We currently check whether a reference has a "match" (i.e. a complementary reference logged by the other user) whenever a mod approves it. However, this causes matches to get missed if a mod approves a ref and the other user hasn't added it yet.
This change makes it so that whenever a ref is added, the server runs a check to see if the new ref has an approved match. If so, it approves and verifies both trades.

Check whether references should be double-approved as soon as they're added

---

assets/userCtrl.js

So to be honest, I have no idea why this was working in Chrome and not Firefox, but this seems to fix it.

Fix an issue where profiles couldn't be viewed in Firefox when the user was logged out

---

assets/app.js

Angular 1.5.9 changed the default hashPrefix from '' to '!' and our version range for angular caused us to go past that version, breaking the https://hq.porygon.co/#/flairtext link used for setting flair text.
This is the same solution we used [for Porybox](https://github.com/porybox/porybox/commit/f4f82bc1be2f0e34b3e22bc044b14efa9555c44c).

Fix for direct links to the set flair modal

---

api/services/Reddit.js

Updated the search query for SVeX threads to hopefully provide better compatibility with [recent changes](https://www.reddit.com/r/changelog/comments/694o34/reddit_search_performance_improvements/) to the search engine. Unfortunately, the search engine is being very unpredictably at the moment, with the same query not always returning the same results if run consecutively. This still brings the current failure rate down somewhat from 100%, though, and should work properly once things are fixed.

Updated search query for SVeX threads

---

assets/styles/bootstrap/panels.less

Added word wrap to the panel body so that it wouldn't overflow. Fixes #568
Preview: https://usercontent.irccloud-cdn.com/file/VFOS7dkA/image.png

Fix note overflow in public notes

---

config/policies.js

Adjust policies to allow flair mods to approve and deny apps (tested on local instance)

Adjust flair mod permissions to allow for approving and denying apps

---

.travis.yml
README.md

Fixes the build tests, which fail after updating npm due to npm changes that break compatibility with Node 4.x.

Update minimum Node.js version required to 6.x

---

api/controllers/UserController.js

Fixes an issue where a 500 error is returned due to non-existent flair text now being returned as a null value rather than an empty string.

Modify ban process function to avoid 500 error when flair is null
